# Jekyll config file for sfuco-site
# Reinier E.
# 2016

# Technical networking
markdown: kramdown
baseurl: ""
url: "sfuco.github.io"
exclude: ['README.md', 'LICENSE.txt', 'node_modules', 'gulpfile.js']

# Content
title: sfuco.
description: sfu concert orchestra's homepage
favicon: img/favicons/sfuco_favicon.png

# Collections: For managing non-post content
collections:
  pages:
    output: true
  execs:
    output: true
